"""Remove attachment columns and attachments table

Revision ID: 0998089c9088
Revises: bee62ef1fba1
Create Date: 2026-04-23 03:04:10.901730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0998089c9088'
down_revision = 'bee62ef1fba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('attachment_filename')
        batch_op.drop_column('attachment_original_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_original_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_filename', sa.VARCHAR(length=255), nullable=True))

    op.create_table('attachments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stored_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('size_bytes', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('entry_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
