"""add content column to entries

Revision ID: 909169e41ae6
Revises: aff9e4282d62
Create Date: 2026-04-21 10:18:59.698488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909169e41ae6'
down_revision = 'aff9e4282d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
